name: pyLife_pragtic
dependencies:
  - python=3.10
  - pip
  - setuptools
  - pip:
    - pip-tools
    - pyLife
    - jupyter
    - pandas
    - plotly
    - streamlit
    - trame-vtk
    - trame-vuetify
    - trame[all]
    - vtk
    - pyvista
